/* dbus_introspect.c generated by valac 0.18.1, the Vala compiler
 * generated from dbus_introspect.vala, do not modify */

/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * dbus_introspect.vala
 * Copyright (C) 2012 Adam and Monica Stark <adstark1982@yahoo.com>
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Adam and Monica Stark'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 * 
 * dbus-introspect IS PROVIDED BY Adam and Monica Stark ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Adam and Monica Stark OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define TYPE_INTROSPECTABLE (introspectable_get_type ())
#define INTROSPECTABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_INTROSPECTABLE, Introspectable))
#define IS_INTROSPECTABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_INTROSPECTABLE))
#define INTROSPECTABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_INTROSPECTABLE, IntrospectableIface))

typedef struct _Introspectable Introspectable;
typedef struct _IntrospectableIface IntrospectableIface;

#define TYPE_INTROSPECTABLE_PROXY (introspectable_proxy_get_type ())
typedef GDBusProxy IntrospectableProxy;
typedef GDBusProxyClass IntrospectableProxyClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_INTROSPECTABLE_SYNC (introspectable_sync_get_type ())
#define INTROSPECTABLE_SYNC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_INTROSPECTABLE_SYNC, IntrospectableSync))
#define IS_INTROSPECTABLE_SYNC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_INTROSPECTABLE_SYNC))
#define INTROSPECTABLE_SYNC_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_INTROSPECTABLE_SYNC, IntrospectableSyncIface))

typedef struct _IntrospectableSync IntrospectableSync;
typedef struct _IntrospectableSyncIface IntrospectableSyncIface;

#define TYPE_INTROSPECTABLE_SYNC_PROXY (introspectable_sync_proxy_get_type ())
typedef GDBusProxy IntrospectableSyncProxy;
typedef GDBusProxyClass IntrospectableSyncProxyClass;

#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _IntrospectableIface {
	GTypeInterface parent_iface;
	gchar* (*introspect) (Introspectable* self, GError** error);
};

struct _IntrospectableSyncIface {
	GTypeInterface parent_iface;
	gchar* (*introspect) (IntrospectableSync* self, GError** error);
};

struct _Main {
	GObject parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GObjectClass parent_class;
};


static gpointer main_parent_class = NULL;
static gboolean main_use_system;
static gboolean main_use_system = FALSE;

GType introspectable_proxy_get_type (void) G_GNUC_CONST;
guint introspectable_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType introspectable_get_type (void) G_GNUC_CONST;
gchar* introspectable_introspect (Introspectable* self, GError** error);
static void introspectable_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static gchar* introspectable_proxy_introspect (Introspectable* self, GError** error);
static void introspectable_proxy_introspectable_interface_init (IntrospectableIface* iface);
static void _dbus_introspectable_introspect (Introspectable* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void introspectable_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* introspectable_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean introspectable_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _introspectable_unregister_object (gpointer user_data);
GType introspectable_sync_proxy_get_type (void) G_GNUC_CONST;
guint introspectable_sync_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType introspectable_sync_get_type (void) G_GNUC_CONST;
gchar* introspectable_sync_introspect (IntrospectableSync* self, GError** error);
static void introspectable_sync_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static gchar* introspectable_sync_proxy_introspect (IntrospectableSync* self, GError** error);
static void introspectable_sync_proxy_introspectable_sync_interface_init (IntrospectableSyncIface* iface);
static void _dbus_introspectable_sync_introspect (IntrospectableSync* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void introspectable_sync_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* introspectable_sync_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean introspectable_sync_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _introspectable_sync_unregister_object (gpointer user_data);
GType main_get_type (void) G_GNUC_CONST;
enum  {
	MAIN_DUMMY_PROPERTY
};
static gchar* main_introspect (const gchar* address, const gchar* path, GError** error);
static gint main_main (gchar** args, int args_length1);
Main* main_new (void);
Main* main_construct (GType object_type);
static void main_finalize (GObject* obj);

static const GDBusArgInfo _introspectable_dbus_arg_info_introspect_result = {-1, "result", "s"};
static const GDBusArgInfo * const _introspectable_dbus_arg_info_introspect_in[] = {NULL};
static const GDBusArgInfo * const _introspectable_dbus_arg_info_introspect_out[] = {&_introspectable_dbus_arg_info_introspect_result, NULL};
static const GDBusMethodInfo _introspectable_dbus_method_info_introspect = {-1, "Introspect", (GDBusArgInfo **) (&_introspectable_dbus_arg_info_introspect_in), (GDBusArgInfo **) (&_introspectable_dbus_arg_info_introspect_out)};
static const GDBusMethodInfo * const _introspectable_dbus_method_info[] = {&_introspectable_dbus_method_info_introspect, NULL};
static const GDBusSignalInfo * const _introspectable_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _introspectable_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _introspectable_dbus_interface_info = {-1, "org.freedesktop.DBus.Introspectable", (GDBusMethodInfo **) (&_introspectable_dbus_method_info), (GDBusSignalInfo **) (&_introspectable_dbus_signal_info), (GDBusPropertyInfo **) (&_introspectable_dbus_property_info)};
static const GDBusInterfaceVTable _introspectable_dbus_interface_vtable = {introspectable_dbus_interface_method_call, introspectable_dbus_interface_get_property, introspectable_dbus_interface_set_property};
static const GDBusArgInfo _introspectable_sync_dbus_arg_info_introspect_result = {-1, "result", "s"};
static const GDBusArgInfo * const _introspectable_sync_dbus_arg_info_introspect_in[] = {NULL};
static const GDBusArgInfo * const _introspectable_sync_dbus_arg_info_introspect_out[] = {&_introspectable_sync_dbus_arg_info_introspect_result, NULL};
static const GDBusMethodInfo _introspectable_sync_dbus_method_info_introspect = {-1, "Introspect", (GDBusArgInfo **) (&_introspectable_sync_dbus_arg_info_introspect_in), (GDBusArgInfo **) (&_introspectable_sync_dbus_arg_info_introspect_out)};
static const GDBusMethodInfo * const _introspectable_sync_dbus_method_info[] = {&_introspectable_sync_dbus_method_info_introspect, NULL};
static const GDBusSignalInfo * const _introspectable_sync_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _introspectable_sync_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _introspectable_sync_dbus_interface_info = {-1, "org.freedesktop.DBus.Introspectable", (GDBusMethodInfo **) (&_introspectable_sync_dbus_method_info), (GDBusSignalInfo **) (&_introspectable_sync_dbus_signal_info), (GDBusPropertyInfo **) (&_introspectable_sync_dbus_property_info)};
static const GDBusInterfaceVTable _introspectable_sync_dbus_interface_vtable = {introspectable_sync_dbus_interface_method_call, introspectable_sync_dbus_interface_get_property, introspectable_sync_dbus_interface_set_property};

gchar* introspectable_introspect (Introspectable* self, GError** error) {
	g_return_val_if_fail (self != NULL, NULL);
	return INTROSPECTABLE_GET_INTERFACE (self)->introspect (self, error);
}


static void introspectable_base_init (IntrospectableIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType introspectable_get_type (void) {
	static volatile gsize introspectable_type_id__volatile = 0;
	if (g_once_init_enter (&introspectable_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (IntrospectableIface), (GBaseInitFunc) introspectable_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType introspectable_type_id;
		introspectable_type_id = g_type_register_static (G_TYPE_INTERFACE, "Introspectable", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (introspectable_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (introspectable_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) introspectable_proxy_get_type);
		g_type_set_qdata (introspectable_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freedesktop.DBus.Introspectable");
		g_type_set_qdata (introspectable_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) introspectable_register_object);
		g_once_init_leave (&introspectable_type_id__volatile, introspectable_type_id);
	}
	return introspectable_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (IntrospectableProxy, introspectable_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_INTROSPECTABLE, introspectable_proxy_introspectable_interface_init) )
static void introspectable_proxy_class_init (IntrospectableProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = introspectable_proxy_g_signal;
}


static void introspectable_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void introspectable_proxy_init (IntrospectableProxy* self) {
}


static gchar* introspectable_proxy_introspect (Introspectable* self, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gchar* _result;
	GVariant* _tmp0_;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freedesktop.DBus.Introspectable", "Introspect");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return NULL;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return NULL;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp0_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_dup_string (_tmp0_, NULL);
	g_variant_unref (_tmp0_);
	g_object_unref (_reply_message);
	return _result;
}


static void introspectable_proxy_introspectable_interface_init (IntrospectableIface* iface) {
	iface->introspect = introspectable_proxy_introspect;
}


static void _dbus_introspectable_introspect (Introspectable* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gchar* result;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = introspectable_introspect (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_string (result));
	_g_free0 (result);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void introspectable_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "Introspect") == 0) {
		_dbus_introspectable_introspect (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* introspectable_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean introspectable_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint introspectable_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_introspectable_dbus_interface_info), &_introspectable_dbus_interface_vtable, data, _introspectable_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _introspectable_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


gchar* introspectable_sync_introspect (IntrospectableSync* self, GError** error) {
	g_return_val_if_fail (self != NULL, NULL);
	return INTROSPECTABLE_SYNC_GET_INTERFACE (self)->introspect (self, error);
}


static void introspectable_sync_base_init (IntrospectableSyncIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType introspectable_sync_get_type (void) {
	static volatile gsize introspectable_sync_type_id__volatile = 0;
	if (g_once_init_enter (&introspectable_sync_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (IntrospectableSyncIface), (GBaseInitFunc) introspectable_sync_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType introspectable_sync_type_id;
		introspectable_sync_type_id = g_type_register_static (G_TYPE_INTERFACE, "IntrospectableSync", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (introspectable_sync_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (introspectable_sync_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) introspectable_sync_proxy_get_type);
		g_type_set_qdata (introspectable_sync_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freedesktop.DBus.Introspectable");
		g_type_set_qdata (introspectable_sync_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) introspectable_sync_register_object);
		g_once_init_leave (&introspectable_sync_type_id__volatile, introspectable_sync_type_id);
	}
	return introspectable_sync_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (IntrospectableSyncProxy, introspectable_sync_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_INTROSPECTABLE_SYNC, introspectable_sync_proxy_introspectable_sync_interface_init) )
static void introspectable_sync_proxy_class_init (IntrospectableSyncProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = introspectable_sync_proxy_g_signal;
}


static void introspectable_sync_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void introspectable_sync_proxy_init (IntrospectableSyncProxy* self) {
}


static gchar* introspectable_sync_proxy_introspect (IntrospectableSync* self, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gchar* _result;
	GVariant* _tmp1_;
	G_DBUS_ERROR;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freedesktop.DBus.Introspectable", "Introspect");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return NULL;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return NULL;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp1_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_dup_string (_tmp1_, NULL);
	g_variant_unref (_tmp1_);
	g_object_unref (_reply_message);
	return _result;
}


static void introspectable_sync_proxy_introspectable_sync_interface_init (IntrospectableSyncIface* iface) {
	iface->introspect = introspectable_sync_proxy_introspect;
}


static void _dbus_introspectable_sync_introspect (IntrospectableSync* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gchar* result;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = introspectable_sync_introspect (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_string (result));
	_g_free0 (result);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void introspectable_sync_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "Introspect") == 0) {
		_dbus_introspectable_sync_introspect (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* introspectable_sync_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean introspectable_sync_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint introspectable_sync_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_introspectable_sync_dbus_interface_info), &_introspectable_sync_dbus_interface_vtable, data, _introspectable_sync_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _introspectable_sync_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


static gchar* main_introspect (const gchar* address, const gchar* path, GError** error) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp3_ = NULL;
	gboolean _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	GBusType _tmp8_ = 0;
	gboolean _tmp9_;
	GBusType _tmp10_;
	const gchar* _tmp11_;
	const gchar* _tmp12_;
	Introspectable* _tmp13_ = NULL;
	Introspectable* objRoot;
	Introspectable* _tmp14_;
	Introspectable* _tmp16_;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (address != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = g_variant_is_object_path (_tmp0_);
	if (!_tmp1_) {
		FILE* _tmp2_;
		_tmp2_ = stderr;
		fprintf (_tmp2_, "Object path was invalid.\n");
		result = NULL;
		return result;
	}
	_tmp4_ = main_use_system;
	if (_tmp4_) {
		_tmp3_ = "-s ";
	} else {
		_tmp3_ = "";
	}
	_tmp5_ = _tmp3_;
	_tmp6_ = address;
	_tmp7_ = path;
	g_debug ("dbus_introspect.vala:58: Config: %s%s %s", _tmp5_, _tmp6_, _tmp7_);
	_tmp9_ = main_use_system;
	if (_tmp9_) {
		_tmp8_ = G_BUS_TYPE_SYSTEM;
	} else {
		_tmp8_ = G_BUS_TYPE_SESSION;
	}
	_tmp10_ = _tmp8_;
	_tmp11_ = address;
	_tmp12_ = path;
	_tmp13_ = g_initable_new (TYPE_INTROSPECTABLE_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", _tmp11_, "g-bus-type", _tmp10_, "g-object-path", _tmp12_, "g-interface-name", "org.freedesktop.DBus.Introspectable", NULL);
	objRoot = (Introspectable*) _tmp13_;
	if (_inner_error_ != NULL) {
		if ((_inner_error_->domain == G_DBUS_ERROR) || (_inner_error_->domain == G_IO_ERROR)) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp14_ = objRoot;
	if (_tmp14_ == NULL) {
		FILE* _tmp15_;
		_tmp15_ = stderr;
		fprintf (_tmp15_, "Could not connect to specified object.\n");
		result = NULL;
		_g_object_unref0 (objRoot);
		return result;
	}
	_tmp16_ = objRoot;
	_tmp17_ = introspectable_introspect (_tmp16_, &_inner_error_);
	_tmp18_ = _tmp17_;
	if (_inner_error_ != NULL) {
		if ((_inner_error_->domain == G_DBUS_ERROR) || (_inner_error_->domain == G_IO_ERROR)) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (objRoot);
			return NULL;
		} else {
			_g_object_unref0 (objRoot);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	result = _tmp18_;
	_g_object_unref0 (objRoot);
	return result;
}


static gint main_main (gchar** args, int args_length1) {
	gint result = 0;
	static const GOptionEntry opts[] = {{"session", '\x0', (gint) G_OPTION_FLAG_REVERSE, G_OPTION_ARG_NONE, &main_use_system, "Use the session bus (the default.)", NULL}, {"system", 's', 0, G_OPTION_ARG_NONE, &main_use_system, "Use the system bus.", NULL}, {NULL}};
	GOptionContext* _tmp0_;
	GOptionContext* optParse;
	GOptionContext* _tmp1_;
	gchar* _result_;
	FILE* _tmp36_;
	const gchar* _tmp37_;
	GError * _inner_error_ = NULL;
	_tmp0_ = g_option_context_new ("ADDRESS PATH\n" \
"\n" \
"Print the interfaces of a DBus object that exposes the \"org.freedskto" \
"p.DBus.Introspectable\" interface.");
	optParse = _tmp0_;
	_tmp1_ = optParse;
	g_option_context_add_main_entries (_tmp1_, opts, NULL);
	{
		GOptionContext* _tmp2_;
		_tmp2_ = optParse;
		g_option_context_parse (_tmp2_, &args_length1, &args, &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch0_g_option_error;
			}
			_g_option_context_free0 (optParse);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
	}
	goto __finally0;
	__catch0_g_option_error:
	{
		GError* e = NULL;
		FILE* _tmp3_;
		GError* _tmp4_;
		const gchar* _tmp5_;
		GOptionContext* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp3_ = stderr;
		_tmp4_ = e;
		_tmp5_ = _tmp4_->message;
		_tmp6_ = optParse;
		_tmp7_ = g_option_context_get_help (_tmp6_, FALSE, NULL);
		_tmp8_ = _tmp7_;
		fprintf (_tmp3_, "%s\n%s\n", _tmp5_, _tmp8_);
		_g_free0 (_tmp8_);
		result = 1;
		_g_error_free0 (e);
		_g_option_context_free0 (optParse);
		return result;
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_option_context_free0 (optParse);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	{
		gchar** _tmp9_;
		gint _tmp9__length1;
		gchar** _tmp14_;
		gint _tmp14__length1;
		_tmp9_ = args;
		_tmp9__length1 = args_length1;
		if (_tmp9__length1 < 2) {
			FILE* _tmp10_;
			GOptionContext* _tmp11_;
			gchar* _tmp12_ = NULL;
			gchar* _tmp13_;
			_tmp10_ = stderr;
			_tmp11_ = optParse;
			_tmp12_ = g_option_context_get_help (_tmp11_, FALSE, NULL);
			_tmp13_ = _tmp12_;
			fprintf (_tmp10_, "You must specify an address.\n%s", _tmp13_);
			_g_free0 (_tmp13_);
			result = 1;
			_g_option_context_free0 (optParse);
			return result;
		}
		_tmp14_ = args;
		_tmp14__length1 = args_length1;
		if (_tmp14__length1 < 3) {
			FILE* _tmp15_;
			GOptionContext* _tmp16_;
			gchar* _tmp17_ = NULL;
			gchar* _tmp18_;
			_tmp15_ = stderr;
			_tmp16_ = optParse;
			_tmp17_ = g_option_context_get_help (_tmp16_, FALSE, NULL);
			_tmp18_ = _tmp17_;
			fprintf (_tmp15_, "You must specify an object path.\n%s", _tmp18_);
			_g_free0 (_tmp18_);
			result = 1;
			_g_option_context_free0 (optParse);
			return result;
		} else {
			gchar** _tmp19_;
			gint _tmp19__length1;
			_tmp19_ = args;
			_tmp19__length1 = args_length1;
			if (_tmp19__length1 > 3) {
				FILE* _tmp20_;
				gchar** _tmp21_;
				gint _tmp21__length1;
				const gchar* _tmp22_;
				GOptionContext* _tmp23_;
				gchar* _tmp24_ = NULL;
				gchar* _tmp25_;
				_tmp20_ = stderr;
				_tmp21_ = args;
				_tmp21__length1 = args_length1;
				_tmp22_ = _tmp21_[3];
				_tmp23_ = optParse;
				_tmp24_ = g_option_context_get_help (_tmp23_, FALSE, NULL);
				_tmp25_ = _tmp24_;
				fprintf (_tmp20_, "Unknown argument: %s\n%s\n", _tmp22_, _tmp25_);
				_g_free0 (_tmp25_);
				result = 1;
				_g_option_context_free0 (optParse);
				return result;
			}
		}
	}
	_result_ = NULL;
	{
		gchar** _tmp26_;
		gint _tmp26__length1;
		const gchar* _tmp27_;
		gchar** _tmp28_;
		gint _tmp28__length1;
		const gchar* _tmp29_;
		gchar* _tmp30_ = NULL;
		gchar* _tmp31_;
		const gchar* _tmp32_;
		_tmp26_ = args;
		_tmp26__length1 = args_length1;
		_tmp27_ = _tmp26_[1];
		_tmp28_ = args;
		_tmp28__length1 = args_length1;
		_tmp29_ = _tmp28_[2];
		_tmp30_ = main_introspect (_tmp27_, _tmp29_, &_inner_error_);
		_tmp31_ = _tmp30_;
		if (_inner_error_ != NULL) {
			goto __catch1_g_error;
		}
		_g_free0 (_result_);
		_result_ = _tmp31_;
		_tmp32_ = _result_;
		if (_tmp32_ == NULL) {
			result = 1;
			_g_free0 (_result_);
			_g_option_context_free0 (optParse);
			return result;
		}
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		FILE* _tmp33_;
		GError* _tmp34_;
		const gchar* _tmp35_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp33_ = stderr;
		_tmp34_ = e;
		_tmp35_ = _tmp34_->message;
		fprintf (_tmp33_, "%s\n", _tmp35_);
		result = 1;
		_g_error_free0 (e);
		_g_free0 (_result_);
		_g_option_context_free0 (optParse);
		return result;
	}
	__finally1:
	if (_inner_error_ != NULL) {
		_g_free0 (_result_);
		_g_option_context_free0 (optParse);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	_tmp36_ = stdout;
	_tmp37_ = _result_;
	fprintf (_tmp36_, "%s", _tmp37_);
	result = 0;
	_g_free0 (_result_);
	_g_option_context_free0 (optParse);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return main_main (argv, argc);
}


Main* main_construct (GType object_type) {
	Main * self = NULL;
	self = (Main*) g_object_new (object_type, NULL);
	return self;
}


Main* main_new (void) {
	return main_construct (TYPE_MAIN);
}


static void main_class_init (MainClass * klass) {
	main_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = main_finalize;
}


static void main_instance_init (Main * self) {
}


static void main_finalize (GObject* obj) {
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
	G_OBJECT_CLASS (main_parent_class)->finalize (obj);
}


GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (G_TYPE_OBJECT, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}



