#!/usr/bin/env python

def build(bld):
	prog = bld(
	      features  = 'c cprogram',
          cflags    = ['-g3', '-ggdb3', '-O0'],
          valaflags = ['-g', '--define=DEBUG'],
          vapi_dirs = ['.'],
          name = 'dbus-introspect.program',
          uselib = ['GIO','DBUS'],
          target = 'dbus-introspect',
          source = 'dbus_introspect.vala',
          packages = ['gio-2.0','dbus_introspect_util'] 
        )
