#!/usr/bin/env python

def build(bld):
	prog = bld(
          features  = 'cc cprogram',
          cflags    = ['-g3', '-ggdb3', '-O0'],
          valaflags = ['-g', '--define=DEBUG'],
          vapi_dirs = ['.']
        )
	# symbolic name used to reference this object
	prog.name = 'dbus-introspect.program'
	# name of the resulting program
	prog.target = 'dbus-introspect'
	prog.source = 'dbus_introspect.vala'

	# libraries to link against
	prog.uselib = ['GIO','DBUS']

	# Vala packages to use
	prog.packages = ['gio-2.0','dbus_introspect_util']

	# Extra vapi dirs
	# prog.vapi_dirs = '../my_lib'
	# Enable threading
	# prog.threading = True
